name: myenv
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
## nf-core dependencies
#  - conda-forge::python=3.7.3
#  - conda-forge::markdown=3.1.1
#  - conda-forge::pymdown-extensions=6.0
#  - conda-forge::pygments=2.5.2
#  - conda-forge::git
# Add Software dependencies
  - bioconda::fastqc=0.11.8
  - bioconda::multiqc=1.7
  - bioconda::bwa=0.7.17
  - bioconda::samblaster=0.1.26
  - bioconda::bedtools=2.29.2
  - bioconda::trim-galore=0.6.5
  - bioconda::samtools=1.10